# Generated by Django 6.0.7 on 2026-10-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KiranaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('selling_price', models.FloatField()),
                ('cost_price', models.FloatField(default=0)),
                ('category', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sold', models.IntegerField()),
                ('sold_on', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kiranaitem')),
            ],
        ),
    ]
